CREATE TABLE message (
	id VARCHAR(100) PRIMARY KEY NOT NULL,
	user VARCHAR(100) NOT NULL,
	message TEXT NOT NULL,
	parent_id VARCHAR(100),
	thread_id VARCHAR(100),
	cheer BOOLEAN NOT NULL,
	date DATE NOT NULL,
	emote BOOLEAN NOT NULL
)